name: GitHub Actions Demo
run-name: ${{ github.actor }} is automating the workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm i
      - name: Deploy to github Pages
        run: |
          git config --global user.email "harshithakonda21@gmail.com"
          git config --global user.name "SarvariHarshitha"
          git remote set-url origin https://${{secrets.MY_PERSONAL_TOKEN}}@github.com/SarvariHarshitha/portfolio/.git
          npm run dev
      - name: Updating domain
        run: echo "Update Domain"