name: GitHub Actions Demo
run-name: ${{ github.actor }} is automating the workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Install Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "harshithakonda21@gmail.com"
          git config --global user.name "SarvariHarshitha"
          git remote set-url origin https://${{ secrets.MY_PERSONAL_TOKEN }}@github.com/SarvariHarshitha/portfolio.git
          npm run deploy
      - name: Updating domain
        run: echo "Your GitHub Pages site is live at https://SarvariHarshitha.github.io/portfolio/"

